export const SIMPLE_CHALLENGE_POINTS = 5;
export const COMPLEX_CHALLENGE_POINTS = 15;
export const DAILY_CHALLENGE_ROUND_TRACKER_STORAGE_KEY_PREFIX =
  "wordle:daily-challenges:round-tracker";
export const DAILY_CHALLENGES_PROGRESS_UPDATED_EVENT =
  "wordle:daily-challenges:progress-updated";

export const CHALLENGE_CONDITION_KEYS = {
  COMEBACK: "comeback",
  STEADY_PLAYER: "steady_player",
  RISKY: "risky",
  PERSISTENT: "persistent",
  NO_REPEAT_N_LETTERS: "no_repeat_n_letters",
  SAME_N_STARTS: "same_n_starts",
  SAME_N_ENDS: "same_n_ends",
  LATE_WIN: "late_win",
  YELLOW_FOCUS: "yellow_focus",
  ONLY_ONE_VOWEL: "only_one_vowel",
  NO_HINTS: "no_hints",
  SPEEDSTER: "speedster",
  RECKLESS: "reckless",
  PALINDROME_GUESS: "palindrome_guess",
  NO_REPEAT_LETTERS: "no_repeat_letters",
  SAME_START: "same_start",
  ENDS_SAME_LETTER: "ends_same_letter",
  ALPHABETICAL_ORDER: "alphabetical_order",
  GREEN_FOCUS: "green_focus",
  RARE_LETTERS: "rare_letters",
  NO_MISPLACED: "no_misplaced",
  SAME_VOWEL_PATTERN: "same_vowel_pattern",
} as const;

export const SIMPLE_CHALLENGE_CONDITION_KEYS = [
  CHALLENGE_CONDITION_KEYS.COMEBACK,
  CHALLENGE_CONDITION_KEYS.STEADY_PLAYER,
  CHALLENGE_CONDITION_KEYS.RISKY,
  CHALLENGE_CONDITION_KEYS.PERSISTENT,
  CHALLENGE_CONDITION_KEYS.NO_REPEAT_N_LETTERS,
  CHALLENGE_CONDITION_KEYS.SAME_N_STARTS,
  CHALLENGE_CONDITION_KEYS.SAME_N_ENDS,
  CHALLENGE_CONDITION_KEYS.LATE_WIN,
  CHALLENGE_CONDITION_KEYS.YELLOW_FOCUS,
  CHALLENGE_CONDITION_KEYS.ONLY_ONE_VOWEL,
  CHALLENGE_CONDITION_KEYS.NO_HINTS,
] as const;

export const COMPLEX_CHALLENGE_CONDITION_KEYS = [
  CHALLENGE_CONDITION_KEYS.SPEEDSTER,
  CHALLENGE_CONDITION_KEYS.RECKLESS,
  CHALLENGE_CONDITION_KEYS.PALINDROME_GUESS,
  CHALLENGE_CONDITION_KEYS.NO_REPEAT_LETTERS,
  CHALLENGE_CONDITION_KEYS.SAME_START,
  CHALLENGE_CONDITION_KEYS.ENDS_SAME_LETTER,
  CHALLENGE_CONDITION_KEYS.ALPHABETICAL_ORDER,
  CHALLENGE_CONDITION_KEYS.GREEN_FOCUS,
  CHALLENGE_CONDITION_KEYS.RARE_LETTERS,
  CHALLENGE_CONDITION_KEYS.NO_MISPLACED,
  CHALLENGE_CONDITION_KEYS.SAME_VOWEL_PATTERN,
] as const;

export const CHALLENGE_DEFAULT_SIMPLE_PERSISTENT_WINS_TARGET = 2;
export const CHALLENGE_DEFAULT_SIMPLE_NO_REPEAT_N_LETTERS = 2;
export const CHALLENGE_DEFAULT_SIMPLE_SAME_N_STARTS = 2;
export const CHALLENGE_DEFAULT_SIMPLE_SAME_N_ENDS = 2;
export const CHALLENGE_DEFAULT_SIMPLE_LATE_WIN_MAX_DURATION_MS = 180_000;
export const CHALLENGE_DEFAULT_SIMPLE_YELLOW_FOCUS_MIN_PRESENT = 3;

export const CHALLENGE_DEFAULT_COMPLEX_SPEEDSTER_MAX_DURATION_MS = 60_000;
export const CHALLENGE_DEFAULT_COMPLEX_RECKLESS_MIN_REPEATS = 2;
export const CHALLENGE_DEFAULT_COMPLEX_RECKLESS_MAX_REPEATS = 3;
export const CHALLENGE_DEFAULT_COMPLEX_GREEN_FOCUS_MIN_CORRECT = 3;
export const CHALLENGE_DEFAULT_COMPLEX_RARE_LETTERS = [
  "Q",
  "Z",
  "X",
  "J",
] as const;
