export const HARD_MODE_TOTAL_SECONDS = 60;
export const HARD_MODE_FINAL_STRETCH_SECONDS = 15;
export const EASY_MODE_HINT_LIMIT = 2;
export const NORMAL_MODE_HINT_LIMIT = 1;
export const HARD_MODE_HINT_LIMIT = 0;
