export type RuntimeEnv = {
  appVersion: string;
  mode: string;
  baseUrl: string;
  convexUrl?: string;
  wordReportPhoneNumber?: string;
  wordListButtonEnabled: boolean;
  wordReportButtonEnabled: boolean;
  paypalDonationButtonEnabled: boolean;
  shareButtonEnabled: boolean;
  devConsoleEnabled: boolean;
  soundEnabled: boolean;
  hintsEnabled: boolean;
  helpButtonEnabled: boolean;
  challengesEnabled: boolean;
  settingsDrawerEnabled: boolean;
  playOfflineStateEnabled: boolean;
  lightningModeEnabled: boolean;
  timerAutoPauseEnabled: boolean;
  difficultyEasyEnabled: boolean;
  difficultyNormalEnabled: boolean;
  difficultyHardEnabled: boolean;
  difficultyInsaneEnabled: boolean;
  scoreLimit: number;
  wordleGameStorageKey: string;
  paypalDonationButtonUrl?: string;
};
